### ISSUE TITLE
Cant play file thats stored locally?

### ISSUE THREAD

**Issue by jimdog1001** [Baseflow/XamarinMediaManager#840]
I am trying to use this package to play mp3 files that are stored locally. I am using await CrossMediaManager.Current.PlayFromResource("assets:///SaintsVsDemons.mp3"). The file is stored under android in the assets folder and the build action is AndroidAsset. No matter what I try, however, it will not play the local file. Is this a bug? Please help.

**Comment by 4or5trees** [comment]
Hi @jimdog1001, were you able to fix this issue?

I am having the same problem. 

This line properly downloads and plays the file (and the `mediaItem` variable has valid metadata):
```csharp
IMediaItem mediaItem = await CrossMediaManager.Current.Play("https://ia800806.us.archive.org/15/items/Mp3Playlist_555/AaronNeville-CrazyLove.mp3");
```

But the line below does nothing and the resulting `mediaItem` variable has no valid metadata and the `Duration` property is zero across the board. The `long-test` MP3 file itself is valid (duration is 1 min 44 secs)
```csharp
IMediaItem mediaItem = await CrossMediaManager.Current.PlayFromResource("assets:///long-test.mp3");
```

If I change the filename to a non-existing resource, I get a `NullReferenceException`. So it does seem to be able to find the `long-test.mp3` file

**Comment by jimdog1001** [comment]
Hows it going,

I did end up finding the solution, for Android anyways, I haven't tried ios.

1) make sure your file build action is set as AndroidAsset, if you need
help with this let me know

2) even tho this isn't what the instructions say, don't use
playfromresource(). You need to use crossMediaManage.currebt.Play(file)

3) you might already have this but file name needs to be
"file:///android_asset/"filename".mp3

Hope this helps, lmk if you have questions

Thanks,

James

**Comment by 4or5trees** [comment]
@jimdog1001 Thank you so much! You have resolved my issue. (and so quickly too!)

The full working line is now:
```csharp
IMediaItem mediaItem = await CrossMediaManager.Current.Play("file:///android_asset/long-test.mp3");
```

**Comment by jimdog1001** [comment]
Fantastic. No problem! That problem bugged me for a bit haha. Cause they
say to use playfromresource but it jjst doesn't work for some reason. Glad
you got it working.

James

**Comment by drmaven** [comment]
Do you have a solution for iOS as well? Duration doesn't work in iOS either, but the file plays normally

**Comment by DaLegacy** [comment]
Is it possible you can go more in-depth with whats the point of this? -> `IMediaItem mediaItem = await CrossMediaManager.Current.Play("file:///android_asset/long-test.mp3");` I get metadata, I don't need metadata I need a video to play on the screen. Is it possible you can post the whole behind code required to get a video to play on the screen with folder structure because nothing I try works...

**Comment by 4or5trees** [comment]
@DaLegacy The line you quoted is the line that plays the audio file. In my case I do not use the `IMediaItem` variable it returns because all I want is to play the sound file. 

Important to note is that I only worked with short **sound** files and not video files. 

That being said, here is the setup I used to get it working:
- MyProject.Android contains an `Assets` folder
    -  Contents are
        -  `sound-files.json`
            - Contains relative paths to sound files + metadata in folder `sound-files`
            - Example path: `sound-files/Example/Here/There/my-sound-file.ogg`
        - Folder `sound-files`
            - Contains sub-folders containing short sound files in `.ogg` format
 - MyProject.Android `.csproj` includes the JSON file and sound files like this:
```xml
<ItemGroup>
  <AndroidAsset Include="Assets\sound-files.json" />
</ItemGroup>
<!-- Example of sound file: -->
<ItemGroup>
    <AndroidAsset Include="Assets\sound-files\Example\Here\There\my-sound-file.ogg" />
</ItemGroup>
```
 - In MyProject.Android `MainActivity.cs` I read out the JSON sound files in the `OnCreate` method
 ```csharp
 string jsonFileName = "sound-files.json";

string content;
AssetManager assets = this.Assets;
using (StreamReader sr = new StreamReader(assets.Open(jsonFileName)))
{
    content = sr.ReadToEnd();
}
// deserialize as desired
```
- Then in the actual Xamarin.Forms project, I have a bunch of buttons for each sound file
    - Sound file is played on click of the button like this
    ```csharp
     private async void Button_Clicked(object sender, EventArgs e)
     {
        Button clickedButton = (Button)sender;
        string filePath = clickedButton.CommandParameter.ToString();
        IMediaItem mediaItem = await CrossMediaManager.Current.Play($"file:///android_asset/{filePath}");
     }
    ```
